{% set name = "pokerkit" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pokerkit-{{ version }}.tar.gz
  sha256: eecf4f6b35fba8300838e6c5c1868f71a8936f07b29599e25444f87a32eab41f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11

test:
  imports:
    - pokerkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uoftcprg/pokerkit
  summary: A Python package for various poker tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
