{% set name = "pokerkit" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pokerkit-{{ version }}.tar.gz
  sha256: 2bb4b65d43340b219aba44637939b9700633b14882c1ac89b578134b45536ea6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11

test:
  imports:
    - pokerkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uoftcprg/pokerkit
  summary: A Python package for various poker tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
