{% set name = "pokerkit" %}
{% set version = "0.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pokerkit-{{ version }}.tar.gz
  sha256: 772687a9d9150ff100aeb6ca17cb860f5e1c4c8d47dd23cf617d7061d91976de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11

test:
  imports:
    - pokerkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uoftcprg/pokerkit
  summary: A Python package for various poker tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
