{% set name = "pokerkit" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pokerkit-{{ version }}.tar.gz
  sha256: bcb12f63ac8cc8a54c8d455a5ef6b07ae1723dd3a80174e6349e877a41fb4c85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11

test:
  imports:
    - pokerkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uoftcprg/pokerkit
  summary: A Python package for various poker tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
