{% set name = "pokerkit" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pokerkit-{{ version }}.tar.gz
  sha256: 78cefdc8b928fd6ef56cfb4803965ac4f052d890957005b28c22126197a2eca4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
  run:
    - python >=3.11

test:
  imports:
    - pokerkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uoftcprg/pokerkit
  summary: A Python package for various poker tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
